package com.yundongjia.app.user.service;

import java.util.List;

import com.yundongjia.oa.admin.po.TMemberShowtime;
import com.yundongjia.oa.admin.po.TMemberShowtimeExample;

/**
 * Created by ltlxy on 2016/8/23.
 */
public interface MemberShowTimeService  {

    int countByExample(TMemberShowtimeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_goods
     *
     * @ibatorgenerated Tue Aug 23 15:05:31 CST 2016
     */
    int deleteByExample(TMemberShowtimeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_goods
     *
     * @ibatorgenerated Tue Aug 23 15:05:31 CST 2016
     */
    int deleteByPrimaryKey(Integer cardId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_goods
     * @return 
     *
     * @ibatorgenerated Tue Aug 23 15:05:31 CST 2016
     */
    void insert(TMemberShowtime record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_goods
     *
     * @ibatorgenerated Tue Aug 23 15:05:31 CST 2016
     */
    void insertSelective(TMemberShowtime record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_goods
     *
     * @ibatorgenerated Tue Aug 23 15:05:31 CST 2016
     */
    List selectByExample(TMemberShowtimeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_goods
     *
     * @ibatorgenerated Tue Aug 23 15:05:31 CST 2016
     */
    TMemberShowtime selectByPrimaryKey(Integer cardId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_goods
     *
     * @ibatorgenerated Tue Aug 23 15:05:31 CST 2016
     */
    int updateByExampleSelective(TMemberShowtime record, TMemberShowtimeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_goods
     *
     * @ibatorgenerated Tue Aug 23 15:05:31 CST 2016
     */
    int updateByExample(TMemberShowtime record, TMemberShowtimeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_goods
     *
     * @ibatorgenerated Tue Aug 23 15:05:31 CST 2016
     */
    int updateByPrimaryKeySelective(TMemberShowtime record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_goods
     *
     * @ibatorgenerated Tue Aug 23 15:05:31 CST 2016
     */
    int updateByPrimaryKey(TMemberShowtime record);



}
